config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'authentication/sessions#new'

  namespace :authentication, path: '', as: '' do
    resources :users, only: %i[new create]
    resources :sessions, only: %i[new create]
    post 'logout', to: 'sessions#logout'
  end

  resources :notes, except: %i[show]
  get 'notes/sort/:field' => 'notes#sort', as: 'sort_notes'
  get 'notes/search' => 'notes#search', as: 'search_notes'

  get '*path', to: 'errors#not_found'
end

app/models/note.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  body       :text(65535)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_notes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Note < ApplicationRecord
  belongs_to :user
  has_many :note_hashtags
  has_many :hashtags, through: :note_hashtags

  scope :with_string, lambda { |str, user_id|
    where_condition = 'notes.title LIKE ? OR notes.body LIKE ? OR hashtags.name LIKE ? AND notes.user_id = ?'
    joins(:hashtags)
      .where(where_condition, "%#{str}%", "%#{str}%", "%#{str}%", user_id)
      .distinct
  }

  def safe_delete
    note_hashtags.destroy_all
    destroy
  end

  def self.order_by_first_hashtag(user_id, direction)
    direction_quantity = "notes.id, #{direction == 'asc' ? 'MIN' : 'MAX'}(hashtags.id) AS first_hashtag"
    subquery = Note.joins(:hashtags)
                   .where(user_id:)
                   .select(direction_quantity)
                   .group('notes.id')
                   .to_sql


    joins("INNER JOIN (#{subquery}) sub ON sub.id = notes.id")
      .order("sub.first_hashtag #{direction.upcase}")
  end

  def self.get_by_user_ordered_by_field(user_id, field, direction = 'asc')
    where(user_id:).order("#{field} #{direction.upcase}")
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_current_user
  before_action :set_sort_direction, only: %i[sort]
  before_action :set_note, only: %i[edit update destroy]

  def index
    @notes = Note.all and return if @user.nil?

    if @user.config['field'] == 'hashtag'
      @notes = Note.order_by_first_hashtag @user.id, @user.config['direction']
      return
    end
    @notes = Note.get_by_user_ordered_by_field @user.id, @user.config['field'], @user.config['direction']
  end

  def sort
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { render :index, status: :ok, location: @note }
    end
  end

  def new
    @note = Note.new
  end

  def search
    @notes = Note.with_string params['value'], @user.id
  end

  def edit; end

  def create
    create_note
    respond_to do |format|
      if @note.save
        flash[:success] = 'Note was successfully created.'
        format.html { redirect_to notes_url }
        format.json { render :index, status: :created, location: @note }
      else
        p @note.errors
        flash[:danger] = 'Note could not be created.'
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params.except(:hashtags))
        @note.hashtag_ids = set_hashtag_id_list
        @note.save
        flash[:success] = 'Note was successfully updated.'
        format.html { redirect_to notes_url }
        format.json { render :index, status: :ok, location: @note }
      else
        flash[:danger] = 'Note could not be updated.'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.safe_delete

    respond_to do |format|
      flash[:warning] = 'Note was successfully destroyed.'
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private

  def create_note
    @note = Note.new(note_params.except(:hashtags))
    @note.user = @user
    @note.hashtag_ids = set_hashtag_id_list
  end

  def set_hashtag_id_list
    note_params[:hashtags].split(',').map do |hashtag|
      hashtag_record = Hashtag.find_by name: hashtag.strip.gsub(' ', '_')
      next hashtag_record.id unless hashtag_record.nil?

      new_hashtag = Hashtag.new name: hashtag.strip.gsub(' ', '_')
      new_hashtag.save
      new_hashtag.id
    end
  end

  def set_note
    @note = Note.find(params[:id])
    return if @note.user == @user

    flash[:danger] = 'You can only see your notes'
    redirect_to notes_url
  end

  def set_current_user
    if session[:current_user_id].nil?
      flash[:danger] = 'You must be logged in to see this page'
      redirect_to root_path
      return
    end

    @user = User.find(session[:current_user_id])
  end

  def set_sort_direction
    if @user.config['field'] == params[:field]
      @user.config['direction'] = @user.config['direction'] == 'asc' ? 'desc' : 'asc'
    else
      @user.config['field'] = params[:field]
      @user.config['direction'] = 'asc'
    end
    @user.save
  end

  def note_params
    params.require(:note).permit(:body, :title, :user_id, :hashtags)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_nav.html.erb
<nav class="navbar navbar-expand-lg text-bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-auto mt-auto d-flex">
        <li>
          <%= button_to 'Home', notes_path, method: :get, class: "btn btn-block btn-primary btn-lg" %>
        </li>
        <li>
          <%= button_to 'Logout', logout_path, method: :post, class: "btn btn-block btn-primary btn-lg ms-3" %>
        </li>
      </ul>
      <%= form_with(url: search_notes_path, method: :get, class: "d-flex") do |form| %>
        <div class="form-group me-3 mt-1">
          <%= form.text_field :value, class: "form-control mt-auto mb-auto", placeholder: "Search" %>
        </div>
        <div class="form-group">
          <%= form.submit "Search", class: "btn btn-block btn-primary btn-lg"%>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<%= render "shared/flash" %>

app/views/notes/_new.html.erb
<%= form_with scope: :note, url: notes_path, local: true do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Body", style: "height: 420px; resize: none" %>
  </div>
  <div class="form-group">
    <%= f.text_field :hashtags, class: "form-control", placeholder: "Hashtags (comma separated)" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-block btn-primary btn-lg" %>
  </div>
<% end %>

app/views/notes/_notes_table.html.erb
<table class="table table-dark table-hover table-scroll table-striped" id="notesTable">
  <thead>
  <tr>
    <th scope="col"><%= link_to "#", sort_notes_path(field: "id"), class: "nav-link" %></th>
    <th scope="col"><%= link_to "Title", sort_notes_path(field: "title"), class: "nav-link" %></th>
    <th scope="col"><%= link_to "Topic", sort_notes_path(field: "hashtag"), class: "nav-link" %></th>
    <th scope="col"><%= link_to "Date", sort_notes_path(field: "created_at"), class: "nav-link" %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @notes.each do |note| %>
    <tr>
      <th class="align-middle" scope="row"><%= note.id %></th>
      <td class="align-middle"><%= note.title %></td>
      <td class="align-middle"><%= note.hashtags.map {|hashtag| hashtag.name}.sort.join(', ') %></td>
      <td class="align-middle"><%= note.created_at.to_date %></td>
      <td><%= button_to 'Show', edit_note_path(note), method: :get, class: "btn btn-block btn-primary btn-lg" %></td>
      <td><%= button_to 'Delete', note_path(note), method: :delete, class: "btn btn-block btn-primary btn-lg"  %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/notes/edit.html.erb
<%= render partial: "nav" %>
<div class="container-fluid d-flex justify-content-center mt-5 pt-5">
  <div class="card text-bg-dark mb-3" style="width: 70rem;">
    <div class="card-header text-center">
      <h3><%= @user.name %> - My notes</h3>
    </div>
    <div class="card-body card-container">
      <%= form_with(model: @note, local: true) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :body, class: "form-control", placeholder: "Body", style: "height: 430px; resize: none" %>
        </div>
        <div class="form-group">
          <%= f.text_field :hashtags, class: "form-control", placeholder: "Hashtags (comma separated)", value: @note.hashtags.map {|hashtag| hashtag.name }.join(', ') %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: "btn btn-block btn-primary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<%= render partial: "nav" %>
<div class="container-fluid d-flex justify-content-center mt-3 pt-3">
  <div class="card text-bg-dark mb-3 me-5" style="width: 70rem;">
    <div class="card-header text-center">
      <h3>Create Note</h3>
    </div>
    <div class="card-body card-container">
      <div class="card-body card-container">
        <%= render "new" %>
      </div>
    </div>
  </div>
  <div class="card text-bg-dark mb-3" style="width: 70rem;">
    <div class="card-header text-center">
      <h3>My Notes</h3>
    </div>
    <div class="card-body card-container">
      <%= render "notes_table" %>
    </div>
  </div>
</div>

app/views/notes/search.html.erb
<%= render partial: "nav" %>
<div class="container-fluid d-flex justify-content-center mt-5 pt-5">
  <div class="card text-bg-dark mb-3" style="width: 70rem;">
    <div class="card-header text-center">
      <h3>My Notes</h3>
    </div>
    <div class="card-body card-container">
      <table class="table table-dark table-hover table-scroll table-striped" id="notesTable">
        <thead>
        <tr>
          <th scope="col"><%= link_to "#", sort_notes_path(field: "id"), class: "nav-link" %></th>
          <th scope="col"><%= link_to "Title", sort_notes_path(field: "title"), class: "nav-link" %></th>
          <th scope="col"><%= link_to "Topic", sort_notes_path(field: "hashtag"), class: "nav-link" %></th>
          <th scope="col"><%= link_to "Date", sort_notes_path(field: "created_at"), class: "nav-link" %></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @notes.each do |note| %>
          <tr>
            <th class="align-middle" scope="row"><%= note.id %></th>
            <td class="align-middle"><%= note.title %></td>
            <td class="align-middle"><%= note.hashtags.map {|hashtag| hashtag.name}.sort.join(', ') %></td>
            <td class="align-middle"><%= note.created_at.to_date %></td>
            <td><%= button_to 'Show', edit_note_path(note), method: :get, class: "btn btn-block btn-primary btn-lg" %></td>
            <td><%= button_to 'Delete', note_path(note), method: :delete, class: "btn btn-block btn-primary btn-lg"  %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>